### ISSUE TITLE
Input to picardHsMetrics does not match wrapper

### ISSUE THREAD

**Issue by jonca79** [clinical-genomics-uppsala/Twist_DNA#69]
Investigate picardHsMetrics and see why the input file differ from the wrapper.
https://snakemake-wrappers.readthedocs.io/en/0.72.0/wrappers/picard/collecthsmetrics.html

**Comment by Smeds** [comment]
If a reference sequence is provided, this program will calculate both AT_DROPOUT and GC_DROPOUT metrics. Dropout metrics are an attempt to measure the reduced representation of reads, in regions that deviate from 50% G/C content. This reduction in the number of aligned reads is due to the increased numbers of errors associated with sequencing regions with excessive or deficient numbers of G/C bases, ultimately leading to poor mapping efficiencies and lowcoverage in the affected regions.

**Comment by jonca79** [comment]
AT_DROPOUT and GC_DROPOUT are already calculated by GcBiasSummaryMetrics

**Comment by jonca79** [comment]
Reference now provided and the wrapper is used.
